/*******************************************************************************
* File Name: cycfg_usbdev.c
*
* Description:
* USB Device middleware configuration
* This file should not be modified. It was automatically generated by
* USB Configurator 2.40.0.6118
*
********************************************************************************
* \copyright
* Copyright 2025 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_usbdev.h"

/*******************************************************************************
*                       Device Descriptors Initialization
*******************************************************************************/

static uint8_t const usb_deviceDescriptors[] = 
{
/******************************************************************************/
/* Device Descriptor                                                          */
/******************************************************************************/
/* bLength */                                                             0x12U, 
/* bDescriptorType */                                                     0x01U, 
/* bcdUSB */                                                       0x00U, 0x02U, 
/* bDeviceClass */                                                        0x02U, 
/* bDeviceSubClass */                                                     0x00U, 
/* bDeviceProtocol */                                                     0x00U, 
/* bMaxPacketSize0 */                                                     0x08U, 
/* idVendor */                                                     0xB4U, 0x04U, 
/* idProduct */                                                    0x51U, 0x80U, 
/* bcdDevice */                                                    0x00U, 0x00U, 
/* iManufacturer */                                                       0x00U, 
/* iProduct */                                                            0x01U, 
/* iSerialNumber */                                                       0x00U, 
/* bNumConfigurations */                                                  0x01U, 
};

static uint8_t const usb_configurationDescriptors[] = 
{
/******************************************************************************/
/* Configuration Descriptor                                                   */
/******************************************************************************/
/* bLength */                                                             0x09U, 
/* bDescriptorType */                                                     0x02U, 
/* wTotalLength */                                                 0x22U, 0x00U, 
/* bNumInterfaces */                                                      0x01U, 
/* bConfigurationValue */                                                 0x01U, 
/* iConfiguration */                                                      0x00U, 
/* bmAttributes */                                                        0x80U, 
/* bMaxPower */                                                           0x19U, 

/******************************************************************************/
/* HID Alternate Settings                                                     */
/******************************************************************************/
/* bLength */                                                             0x09U, 
/* bDescriptorType */                                                     0x04U, 
/* bInterfaceNumber */                                                    0x00U, 
/* bAlternateSetting */                                                   0x00U, 
/* bNumEndpoints */                                                       0x01U, 
/* bInterfaceClass */                                                     0x03U, 
/* bInterfaceSubClass */                                                  0x00U, 
/* bInterfaceProtocol */                                                  0x00U, 
/* iInterface */                                                          0x00U, 

/******************************************************************************/
/* HID Descriptor                                                             */
/******************************************************************************/
/* bLength */                                                             0x09U, 
/* bDescriptorType */                                                     0x21U, 
/* bcdHID */                                                       0x11U, 0x01U, 
/* bCountryCode */                                                        0x00U, 
/* bNumDescriptors */                                                     0x01U, 
/* bDescriptorType(Report) */                                             0x22U, 
/* wDescriptorLength */                                            0x32U, 0x00U, 

/******************************************************************************/
/* Endpoint Descriptor                                                        */
/******************************************************************************/
/* bLength */                                                             0x07U, 
/* bDescriptorType */                                                     0x05U, 
/* bEndpointAddress */                                                    0x81U, 
/* bmAttributes */                                                        0x02U, 
/* wMaxPacketSize */                                               0x03U, 0x00U, 
/* bInterval */                                                           0x0AU, 
};

static uint8_t const usb_stringDescriptors[] = 
{
/******************************************************************************/
/* Language ID Descriptor                                                     */
/******************************************************************************/
/* bLength */                                                             0x04U, 
/* bDescriptorType */                                                     0x03U, 
/* wLANGID */                                                      0x09U, 0x04U, 

/******************************************************************************/
/* String Descriptor                                                          */
/******************************************************************************/
/* bLength */                                                             0x3AU, 
/* bDescriptorType */                                                     0x03U, 
/* bString */ 
    (uint8_t)'U', 0U, (uint8_t)'S', 0U, (uint8_t)'B', 0U, (uint8_t)' ', 0U,
    (uint8_t)'D', 0U, (uint8_t)'e', 0U, (uint8_t)'v', 0U, (uint8_t)'i', 0U,
    (uint8_t)'c', 0U, (uint8_t)'e', 0U, (uint8_t)' ', 0U, (uint8_t)'Q', 0U,
    (uint8_t)'u', 0U, (uint8_t)'i', 0U, (uint8_t)'c', 0U, (uint8_t)'k', 0U,
    (uint8_t)' ', 0U, (uint8_t)'S', 0U, (uint8_t)'t', 0U, (uint8_t)'a', 0U,
    (uint8_t)'r', 0U, (uint8_t)'t', 0U, (uint8_t)' ', 0U, (uint8_t)'G', 0U,
    (uint8_t)'u', 0U, (uint8_t)'i', 0U, (uint8_t)'d', 0U, (uint8_t)'e', 0U,
};

static uint8_t const usb_hidReportDescriptors[] = 
{
/* USAGE_PAGE */                                                   0x05U, 0x01U, 
/* USAGE */                                                        0x09U, 0x02U, 
/* COLLECTION */                                                   0xA1U, 0x01U, 
/* USAGE */                                                        0x09U, 0x01U, 
/* COLLECTION */                                                   0xA1U, 0x00U, 
/* USAGE_PAGE */                                                   0x05U, 0x09U, 
/* USAGE_MINIMUM */                                                0x19U, 0x01U, 
/* USAGE_MAXIMUM */                                                0x29U, 0x03U, 
/* LOGICAL_MINIMUM */                                              0x15U, 0x00U, 
/* LOGICAL_MAXIMUM */                                              0x25U, 0x01U, 
/* REPORT_COUNT */                                                 0x95U, 0x03U, 
/* REPORT_SIZE */                                                  0x75U, 0x01U, 
/* INPUT */                                                        0x81U, 0x02U, 
/* REPORT_COUNT */                                                 0x95U, 0x01U, 
/* REPORT_SIZE */                                                  0x75U, 0x05U, 
/* INPUT */                                                        0x81U, 0x01U, 
/* USAGE_PAGE */                                                   0x05U, 0x01U, 
/* USAGE */                                                        0x09U, 0x30U, 
/* USAGE */                                                        0x09U, 0x31U, 
/* LOGICAL_MINIMUM */                                              0x15U, 0x81U, 
/* LOGICAL_MAXIMUM */                                              0x25U, 0x7FU, 
/* REPORT_SIZE */                                                  0x75U, 0x08U, 
/* REPORT_COUNT */                                                 0x95U, 0x02U, 
/* INPUT */                                                        0x81U, 0x06U, 
/* END_COLLECTION */                                                      0xC0U, 
/* END_COLLECTION */                                                      0xC0U, 
};

/*******************************************************************************
*                       Device Structures Initialization
*******************************************************************************/

/* Endpoints array initialization */
static const cy_stc_usb_dev_endpoint_t usb_endpoints[] = 
{
    {
        .endpointDescriptor = &usb_configurationDescriptors[27], 
    },
};

/* Pointers to endpoints array initialization */
static const cy_stc_usb_dev_endpoint_t* usb_endpointsPtr[] = 
{
    &usb_endpoints[0],
};

static const uint8_t usb_hidReportIdx[] =
{
    1U,
};

/* HID array initialization */
static const cy_stc_usb_dev_hid_t  usb_hid[] = 
{
    {
        .hidDescriptor        = &usb_configurationDescriptors[18], 
        .reportDescriptor     = &usb_hidReportDescriptors[0],
        .reportDescriptorSize = 50U,
        .inputReportPos       = 0U,
        .numInputReports      = 1U,
        .inputReportIdx       = &usb_hidReportIdx[0],
        .inputReportIdxSize   = 1U,
    },
};

/* Alternate settings array initialization */
static const cy_stc_usb_dev_alternate_t usb_alternates[] = 
{
    {
        .interfaceDescriptor = &usb_configurationDescriptors[9],
        .numEndpoints        = 1U,
        .endpoints           = &usb_endpointsPtr[0],
        .hid                 = &usb_hid[0],
    },
};

/* Pointers to alternates array initialization */
static const cy_stc_usb_dev_alternate_t* usb_alternatesPtr[] = 
{
    &usb_alternates[0],
};

/* Interfaces array initialization */
static const cy_stc_usb_dev_interface_t usb_interfaces[] =
{
    {
        .numAlternates = 1U,
        .alternates    = &usb_alternatesPtr[0],
        .endpointsMask = 0x0001U,
    },
};

/* Pointers to interfaces array initialization */
static const cy_stc_usb_dev_interface_t* usb_interfacesPtr[] = 
{
    &usb_interfaces[0],
};

/* Configurations array initialization */
static const cy_stc_usb_dev_configuration_t  usb_configurations[] =
{
    {
        .configDescriptor = &usb_configurationDescriptors[0],
        .numInterfaces    = 1U,
        .interfaces       = &usb_interfacesPtr[0],
    },
};

/* Pointers to configurations array initialization */
static const cy_stc_usb_dev_configuration_t* usb_configurationsPtr[] = 
{
    &usb_configurations[0],
};

/* Pointers to Strings array initialization */
static const uint8_t* usb_stringPtr[] = 
{
    &usb_stringDescriptors[0],
    &usb_stringDescriptors[4],

};

/* String array initialization */
static const cy_stc_usb_dev_string_t  usb_strings[] =
{
    {
        .numStrings                = 2U,
        .stringDescriptors         = &usb_stringPtr[0],
        .osStringDescriptors       = NULL,
    },
};

/* Device array initialization */
const cy_stc_usb_dev_device_t usb_devices[] =
{
    {
        .deviceDescriptor  = &usb_deviceDescriptors[0],
        .bosDescriptor     = NULL, 
        .strings           = &usb_strings[0], 
        .numConfigurations = 1U, 
        .configurations    = &usb_configurationsPtr[0], 
    },
};

/* HID configuration */
static uint8_t idleTimers[2U * 1U];
const cy_stc_usb_dev_hid_config_t usb_hidConfig = 
{
    .timers    = idleTimers,
    .timersNum = 1U,
};

/* Device configuration */
static uint8_t endpoint0Buffer[64U];
const cy_stc_usb_dev_config_t usb_devConfig = 
{
    .ep0Buffer     = endpoint0Buffer,
    .ep0BufferSize = 64U,
};

/* [] END OF FILE */
