FROM ubuntu:20.04

# Install necessary packages
RUN DEBIAN_FRONTEND=noninteractive \
	apt-get update	\ 
	&& apt-get install -y wget make git cppcheck ca-certificates clang-format-12 

# add cpio
RUN apt-get install cpio libncurses5 -y

# get the toolchain
RUN wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 -O gcc-arm-none-eabi.tar.bz2

# unpack the archive to a neatly named target directory
RUN mkdir gcc-arm-none-eabi && tar xjfv gcc-arm-none-eabi.tar.bz2 -C gcc-arm-none-eabi --strip-components 1
# remove the archive
RUN rm gcc-arm-none-eabi.tar.bz2

# add the tools to the path
ENV PATH="/gcc-arm-none-eabi/bin:${PATH}"

# Create a non-root user named "ubuntu"
# But put in the root group since GitHub actions needs permissions
# to create tmp files
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo \
	-u 1001 ubuntu
USER ubuntu
WORKDIR /home/ubuntu
