on:[push]
jobs:
	build_and_static_analysis:
  		runs-on: ubuntu-latest
   		container:
			image: hariudkmr/sumobot:latest
   		steps:
			-name: checkout the repository
	 		uses: actions/checkout@v3
			-run: make
			-run: make codecheck
	
