name: sumobot ci setup
# This workflow sets up the continuous integration flow for the psoc6 project

on: [push]

jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: hariudkmr/sumobot:latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make
      - run: make codecheck
